package vavi.util.archive.xad.xadmaster;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * Own date structure to cover all possible dates in a human friendly<br>
 * format. xadConvertDates may be used to convert between different date<br>
 * structures and variables.<br>
 * <i>native declaration : /Frameworks/XADMaster.framework/Versions/A/Headers/xadmaster.h:248</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xadDate extends Structure {
	/**
	 * values 0 to 999999<br>
	 * C type : xadUINT32
	 */
	public int xd_Micros;
	/**
	 * values 1 to 2147483648<br>
	 * C type : xadINT32
	 */
	public int xd_Year;
	/**
	 * values 1 to 12<br>
	 * C type : xadUINT8
	 */
	public byte xd_Month;
	/**
	 * values 1 to 7<br>
	 * C type : xadUINT8
	 */
	public byte xd_WeekDay;
	/**
	 * values 1 to 31<br>
	 * C type : xadUINT8
	 */
	public byte xd_Day;
	/**
	 * values 0 to 23<br>
	 * C type : xadUINT8
	 */
	public byte xd_Hour;
	/**
	 * values 0 to 59<br>
	 * C type : xadUINT8
	 */
	public byte xd_Minute;
	/**
	 * values 0 to 59<br>
	 * C type : xadUINT8
	 */
	public byte xd_Second;
	public xadDate() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("xd_Micros", "xd_Year", "xd_Month", "xd_WeekDay", "xd_Day", "xd_Hour", "xd_Minute", "xd_Second");
	}
	/**
	 * @param xd_Micros values 0 to 999999<br>
	 * C type : xadUINT32<br>
	 * @param xd_Year values 1 to 2147483648<br>
	 * C type : xadINT32<br>
	 * @param xd_Month values 1 to 12<br>
	 * C type : xadUINT8<br>
	 * @param xd_WeekDay values 1 to 7<br>
	 * C type : xadUINT8<br>
	 * @param xd_Day values 1 to 31<br>
	 * C type : xadUINT8<br>
	 * @param xd_Hour values 0 to 23<br>
	 * C type : xadUINT8<br>
	 * @param xd_Minute values 0 to 59<br>
	 * C type : xadUINT8<br>
	 * @param xd_Second values 0 to 59<br>
	 * C type : xadUINT8
	 */
	public xadDate(int xd_Micros, int xd_Year, byte xd_Month, byte xd_WeekDay, byte xd_Day, byte xd_Hour, byte xd_Minute, byte xd_Second) {
		super();
		this.xd_Micros = xd_Micros;
		this.xd_Year = xd_Year;
		this.xd_Month = xd_Month;
		this.xd_WeekDay = xd_WeekDay;
		this.xd_Day = xd_Day;
		this.xd_Hour = xd_Hour;
		this.xd_Minute = xd_Minute;
		this.xd_Second = xd_Second;
	}
	public xadDate(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xadDate implements Structure.ByReference {
		
	};
	public static class ByValue extends xadDate implements Structure.ByValue {
		
	};
}
