package vavi.util.archive.xad.xadmaster;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import com.sun.jna.Union;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /Frameworks/XADMaster.framework/Versions/A/Headers/xadmaster.h:448</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xadSpecial extends Structure {
	/**
	 * XADSPECIALTYPE to define type of block (V11)<br>
	 * C type : xadUINT32
	 */
	public int xfis_Type;
	/**
	 * pointer to next entry<br>
	 * C type : xadSpecial*
	 */
	public xadSpecial.ByReference xfis_Next;
	/** C type : xfis_Data_union */
	public xfis_Data_union xfis_Data;
	/** <i>native declaration : /Frameworks/XADMaster.framework/Versions/A/Headers/xadmaster.h:452</i> */
	public static class xfis_Data_union extends Union {
		/** C type : xadSpecialUnixDevice */
		public xadSpecialUnixDevice xfis_UnixDevice;
		/** C type : xadSpecialAmigaAddress */
		public xadSpecialAmigaAddress xfis_AmigaAddress;
		/** C type : xadSpecialCBM8bit */
		public xadSpecialCBM8bit xfis_CBM8bit;
		public xfis_Data_union() {
			super();
		}
		/** @param xfis_UnixDevice C type : xadSpecialUnixDevice */
		public xfis_Data_union(xadSpecialUnixDevice xfis_UnixDevice) {
			super();
			this.xfis_UnixDevice = xfis_UnixDevice;
			setType(xadSpecialUnixDevice.class);
		}
		/** @param xfis_AmigaAddress C type : xadSpecialAmigaAddress */
		public xfis_Data_union(xadSpecialAmigaAddress xfis_AmigaAddress) {
			super();
			this.xfis_AmigaAddress = xfis_AmigaAddress;
			setType(xadSpecialAmigaAddress.class);
		}
		/** @param xfis_CBM8bit C type : xadSpecialCBM8bit */
		public xfis_Data_union(xadSpecialCBM8bit xfis_CBM8bit) {
			super();
			this.xfis_CBM8bit = xfis_CBM8bit;
			setType(xadSpecialCBM8bit.class);
		}
		public xfis_Data_union(Pointer peer) {
			super(peer);
		}
		public static class ByReference extends xfis_Data_union implements Structure.ByReference {
			
		};
		public static class ByValue extends xfis_Data_union implements Structure.ByValue {
			
		};
	};
	public xadSpecial() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("xfis_Type", "xfis_Next", "xfis_Data");
	}
	/**
	 * @param xfis_Type XADSPECIALTYPE to define type of block (V11)<br>
	 * C type : xadUINT32<br>
	 * @param xfis_Next pointer to next entry<br>
	 * C type : xadSpecial*<br>
	 * @param xfis_Data C type : xfis_Data_union
	 */
	public xadSpecial(int xfis_Type, xadSpecial.ByReference xfis_Next, xfis_Data_union xfis_Data) {
		super();
		this.xfis_Type = xfis_Type;
		this.xfis_Next = xfis_Next;
		this.xfis_Data = xfis_Data;
	}
	public xadSpecial(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xadSpecial implements Structure.ByReference {
		
	};
	public static class ByValue extends xadSpecial implements Structure.ByValue {
		
	};
}
