package vavi.util.archive.xad.xadmaster;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /Frameworks/XADMaster.framework/Versions/A/Headers/xadmaster.h:426</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xadSpecialAmigaAddress extends Structure {
	/**
	 * code execution start address<br>
	 * C type : xadUINT32
	 */
	public int xfis_JumpAddress;
	/**
	 * decrunch start of code<br>
	 * C type : xadUINT32
	 */
	public int xfis_DecrunchAddress;
	public xadSpecialAmigaAddress() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("xfis_JumpAddress", "xfis_DecrunchAddress");
	}
	/**
	 * @param xfis_JumpAddress code execution start address<br>
	 * C type : xadUINT32<br>
	 * @param xfis_DecrunchAddress decrunch start of code<br>
	 * C type : xadUINT32
	 */
	public xadSpecialAmigaAddress(int xfis_JumpAddress, int xfis_DecrunchAddress) {
		super();
		this.xfis_JumpAddress = xfis_JumpAddress;
		this.xfis_DecrunchAddress = xfis_DecrunchAddress;
	}
	public xadSpecialAmigaAddress(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xadSpecialAmigaAddress implements Structure.ByReference {
		
	};
	public static class ByValue extends xadSpecialAmigaAddress implements Structure.ByValue {
		
	};
}
