package vavi.util.archive.xad.xadmaster;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /Frameworks/XADMaster.framework/Versions/A/Headers/xadmaster.h:280</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xadSkipInfo extends Structure {
	/** C type : xadSkipInfo* */
	public xadSkipInfo.ByReference xsi_Next;
	/**
	 * position, where it should be skipped<br>
	 * C type : xadSize
	 */
	public long xsi_Position;
	/**
	 * size to skip<br>
	 * C type : xadSize
	 */
	public long xsi_SkipSize;
	public xadSkipInfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("xsi_Next", "xsi_Position", "xsi_SkipSize");
	}
	/**
	 * @param xsi_Next C type : xadSkipInfo*<br>
	 * @param xsi_Position position, where it should be skipped<br>
	 * C type : xadSize<br>
	 * @param xsi_SkipSize size to skip<br>
	 * C type : xadSize
	 */
	public xadSkipInfo(xadSkipInfo.ByReference xsi_Next, long xsi_Position, long xsi_SkipSize) {
		super();
		this.xsi_Next = xsi_Next;
		this.xsi_Position = xsi_Position;
		this.xsi_SkipSize = xsi_SkipSize;
	}
	public xadSkipInfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xadSkipInfo implements Structure.ByReference {
		
	};
	public static class ByValue extends xadSkipInfo implements Structure.ByValue {
		
	};
}
