package vavi.util.archive.unar.xadmaster;
import com.sun.jna.Library;
import com.sun.jna.Native;
import com.sun.jna.NativeLibrary;
import com.sun.jna.Pointer;
import java.nio.ByteBuffer;
/**
 * JNA Wrapper for library <b>xadmaster</b><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public interface XadmasterLibrary extends Library {
	String JNA_LIBRARY_NAME = "XADMaster";
	NativeLibrary JNA_NATIVE_LIB = NativeLibrary.getInstance(XadmasterLibrary.JNA_LIBRARY_NAME);
	XadmasterLibrary INSTANCE = Native.load(XadmasterLibrary.JNA_LIBRARY_NAME, XadmasterLibrary.class);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFALSE = 0;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADTRUE = 1;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADMEMF_ANY = (0);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADMEMF_CLEAR = (1 << 16);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADMEMF_PUBLIC = (1 << 0);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int TAG_PTR = (0x80000000);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int TAG_INT = (0x40000000);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int TAG_SIZ = (0x20000000);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int TAG_DONE = ((0x40000000) + 0x10000000);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int TAG_IGNORE = ((0x40000000) + 0x10000001);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int TAG_MORE = ((0x80000000) + 0x10000002);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int TAG_SKIP = ((0x40000000) + 0x10000003);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_INSIZE = ((0x20000000) + 1);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_INFILENAME = ((0x80000000) + 2);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_INFILEHANDLE = ((0x80000000) + 3);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_INMEMORY = ((0x80000000) + 4);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_INHOOK = ((0x80000000) + 5);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_INSPLITTED = ((0x80000000) + 6);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_INDISKARCHIVE = ((0x80000000) + 7);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_INXADSTREAM = ((0x80000000) + 8);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_INDEVICE = ((0x80000000) + 9);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_OUTSIZE = ((0x20000000) + 10);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_OUTFILENAME = ((0x80000000) + 11);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_OUTFILEHANDLE = ((0x80000000) + 12);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_OUTMEMORY = ((0x80000000) + 13);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_OUTHOOK = ((0x80000000) + 14);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_OUTDEVICE = ((0x80000000) + 15);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_OUTXADSTREAM = ((0x80000000) + 16);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_OBJNAMESIZE = ((0x40000000) + 20);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_OBJCOMMENTSIZE = ((0x40000000) + 21);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_OBJPRIVINFOSIZE = ((0x40000000) + 22);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_OBJBLOCKENTRIES = ((0x40000000) + 23);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_NOEXTERN = ((0x40000000) + 50);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_PASSWORD = ((0x80000000) + 51);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_ENTRYNUMBER = ((0x40000000) + 52);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_PROGRESSHOOK = ((0x80000000) + 53);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_OVERWRITE = ((0x40000000) + 54);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_MAKEDIRECTORY = ((0x40000000) + 55);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_IGNOREGEOMETRY = ((0x40000000) + 56);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_LOWCYLINDER = ((0x40000000) + 57);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_HIGHCYLINDER = ((0x40000000) + 58);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_VERIFY = ((0x40000000) + 59);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_NOKILLPARTIAL = ((0x40000000) + 60);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_FORMAT = ((0x40000000) + 61);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_USESECTORLABELS = ((0x40000000) + 62);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_IGNOREFLAGS = ((0x40000000) + 63);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_ONLYFLAGS = ((0x40000000) + 64);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_CLIENT = ((0x40000000) + 65);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_DATEUNIX = ((0x40000000) + 70);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_DATEAMIGA = ((0x40000000) + 71);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_DATEDATESTAMP = ((0x80000000) + 72);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_DATEXADDATE = ((0x80000000) + 73);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_DATECLOCKDATA = ((0x80000000) + 74);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_DATECURRENTTIME = ((0x40000000) + 75);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_DATEMSDOS = ((0x40000000) + 76);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_DATEMAC = ((0x40000000) + 77);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_DATECPM = ((0x80000000) + 78);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_DATECPM2 = ((0x40000000) + 79);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_DATEISO9660 = ((0x80000000) + 300);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_GETDATEUNIX = ((0x80000000) + 80);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_GETDATEAMIGA = ((0x80000000) + 81);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_GETDATEDATESTAMP = ((0x80000000) + 82);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_GETDATEXADDATE = ((0x80000000) + 83);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_GETDATECLOCKDATA = ((0x80000000) + 84);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_GETDATEMSDOS = ((0x80000000) + 86);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_GETDATEMAC = ((0x80000000) + 87);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_GETDATECPM = ((0x80000000) + 88);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_GETDATECPM2 = ((0x80000000) + 89);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_GETDATEISO9660 = ((0x80000000) + 320);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_MAKEGMTDATE = ((0x40000000) + 90);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_MAKELOCALDATE = ((0x40000000) + 91);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_USESKIPINFO = ((0x40000000) + 104);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_SECTORLABELS = ((0x80000000) + 105);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_GETCRC16 = ((0x80000000) + 120);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_GETCRC32 = ((0x80000000) + 121);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_CRC16ID = ((0x40000000) + 130);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_CRC32ID = ((0x40000000) + 131);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_PROTAMIGA = ((0x40000000) + 160);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_PROTUNIX = ((0x40000000) + 161);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_PROTMSDOS = ((0x40000000) + 162);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_PROTFILEINFO = ((0x80000000) + 163);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_GETPROTAMIGA = ((0x80000000) + 170);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_GETPROTUNIX = ((0x80000000) + 171);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_GETPROTMSDOS = ((0x80000000) + 172);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_GETPROTFILEINFO = ((0x80000000) + 173);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_STARTCLIENT = ((0x80000000) + 180);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_NOEMPTYERROR = ((0x40000000) + 181);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_WASERROR = ((0x40000000) + 190);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_ARCHIVEINFO = ((0x80000000) + 200);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_ERRORCODE = ((0x80000000) + 201);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_EXTENSION = ((0x80000000) + 202);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_SETINPOS = ((0x20000000) + 240);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_INSERTDIRSFIRST = ((0x40000000) + 241);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_PATHSEPERATOR = ((0x80000000) + 260);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_CHARACTERSET = ((0x40000000) + 261);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_STRINGSIZE = ((0x40000000) + 262);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_CSTRING = ((0x80000000) + 263);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_PSTRING = ((0x80000000) + 264);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_XADSTRING = ((0x80000000) + 265);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_ADDPATHSEPERATOR = ((0x40000000) + 266);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_NOLEADINGPATH = ((0x40000000) + 280);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_NOTRAILINGPATH = ((0x40000000) + 281);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_MASKCHARACTERS = ((0x80000000) + 282);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_MASKINGCHAR = ((0x40000000) + 283);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XAD_REQUIREDBUFFERSIZE = ((0x80000000) + 284);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADOBJ_ARCHIVEINFO = 0x0001;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADOBJ_FILEINFO = 0x0002;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADOBJ_DISKINFO = 0x0003;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADOBJ_HOOKPARAM = 0x0004;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADOBJ_DEVICEINFO = 0x0005;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADOBJ_PROGRESSINFO = 0x0006;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADOBJ_TEXTINFO = 0x0007;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADOBJ_SPLITFILE = 0x0008;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADOBJ_SKIPINFO = 0x0009;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADOBJ_IMAGEINFO = 0x000A;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADOBJ_SPECIAL = 0x000B;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADOBJ_MEMBLOCK = 0x0100;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADOBJ_STRING = 0x0101;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCRC16_ID1 = 0xA001;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCRC32_ID1 = 0xEDB88320;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADHC_READ = 1;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADHC_WRITE = 2;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADHC_SEEK = 3;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADHC_INIT = 4;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADHC_FREE = 5;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADHC_ABORT = 6;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADHC_FULLSIZE = 7;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADHC_IMAGEINFO = 8;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAC_READ = 10;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAC_WRITE = 11;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAC_COPY = 12;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAC_INPUTSEEK = 13;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAC_OUTPUTSEEK = 14;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDAY_MONDAY = 1;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDAY_TUESDAY = 2;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDAY_WEDNESDAY = 3;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDAY_THURSDAY = 4;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDAY_FRIDAY = 5;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDAY_SATURDAY = 6;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDAY_SUNDAY = 7;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIB_CRYPTED = 0;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIB_FILECORRUPT = 1;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIB_FILEARCHIVE = 2;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIB_DISKARCHIVE = 3;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIB_OVERWRITE = 4;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIB_MAKEDIRECTORY = 5;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIB_IGNOREGEOMETRY = 6;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIB_VERIFY = 7;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIB_NOKILLPARTIAL = 8;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIB_DISKIMAGE = 9;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIB_FORMAT = 10;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIB_NOEMPTYERROR = 11;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIB_ONLYIN = 12;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIB_ONLYOUT = 13;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIB_USESECTORLABELS = 14;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIF_CRYPTED = (1 << 0);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIF_FILECORRUPT = (1 << 1);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIF_FILEARCHIVE = (1 << 2);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIF_DISKARCHIVE = (1 << 3);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIF_OVERWRITE = (1 << 4);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIF_MAKEDIRECTORY = (1 << 5);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIF_IGNOREGEOMETRY = (1 << 6);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIF_VERIFY = (1 << 7);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIF_NOKILLPARTIAL = (1 << 8);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIF_DISKIMAGE = (1 << 9);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIF_FORMAT = (1 << 10);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIF_NOEMPTYERROR = (1 << 11);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIF_ONLYIN = (1 << 12);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIF_ONLYOUT = (1 << 13);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADAIF_USESECTORLABELS = (1 << 14);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFILETYPE_DATACRUNCHER = 1;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFILETYPE_TEXTLINKER = 2;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFILETYPE_AMIGAEXECRUNCHER = 11;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFILETYPE_AMIGAEXELINKER = 12;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFILETYPE_AMIGATEXTLINKER = 13;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFILETYPE_AMIGAADDRESS = 14;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFILETYPE_UNIXBLOCKDEVICE = 21;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFILETYPE_UNIXCHARDEVICE = 22;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFILETYPE_UNIXFIFO = 23;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFILETYPE_UNIXSOCKET = 24;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFILETYPE_MSDOSEXECRUNCHER = 31;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADSPECIALTYPE_UNIXDEVICE = 1;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADSPECIALTYPE_AMIGAADDRESS = 2;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADSPECIALTYPE_CBM8BIT = 3;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCBM8BITTYPE_UNKNOWN = 0x00;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCBM8BITTYPE_BASIC = 0x01;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCBM8BITTYPE_DATA = 0x02;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCBM8BITTYPE_FIXED = 0x03;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCBM8BITTYPE_SEQDATA = 0x04;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCBM8BITTYPE_SEQ = 0x81;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCBM8BITTYPE_PRG = 0x82;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCBM8BITTYPE_USR = 0x83;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCBM8BITTYPE_REL = 0x84;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCBM8BITTYPE_CBM = 0x85;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_CRYPTED = 0;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_DIRECTORY = 1;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_LINK = 2;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_INFOTEXT = 3;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_GROUPED = 4;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_ENDOFGROUP = 5;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_NODATE = 6;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_DELETED = 7;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_SEEKDATAPOS = 8;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_NOFILENAME = 9;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_NOUNCRUNCHSIZE = 10;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_PARTIALFILE = 11;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_MACDATA = 12;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_MACRESOURCE = 13;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_EXTRACTONBUILD = 14;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_UNIXPROTECTION = 15;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_DOSPROTECTION = 16;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_ENTRYMAYCHANGE = 17;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_XADSTRFILENAME = 18;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_XADSTRLINKNAME = 19;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIB_XADSTRCOMMENT = 20;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_CRYPTED = (1 << 0);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_DIRECTORY = (1 << 1);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_LINK = (1 << 2);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_INFOTEXT = (1 << 3);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_GROUPED = (1 << 4);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_ENDOFGROUP = (1 << 5);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_NODATE = (1 << 6);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_DELETED = (1 << 7);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_SEEKDATAPOS = (1 << 8);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_NOFILENAME = (1 << 9);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_NOUNCRUNCHSIZE = (1 << 10);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_PARTIALFILE = (1 << 11);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_MACDATA = (1 << 12);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_MACRESOURCE = (1 << 13);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_EXTRACTONBUILD = (1 << 14);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_UNIXPROTECTION = (1 << 15);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_DOSPROTECTION = (1 << 16);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_ENTRYMAYCHANGE = (1 << 17);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_XADSTRFILENAME = (1 << 18);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_XADSTRLINKNAME = (1 << 19);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADFIF_XADSTRCOMMENT = (1 << 20);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADTIB_CRYPTED = 0;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADTIB_BANNER = 1;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADTIB_FILEDIZ = 2;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADTIF_CRYPTED = (1 << 0);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADTIF_BANNER = (1 << 1);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADTIF_FILEDIZ = (1 << 2);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_CRYPTED = 0;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_SEEKDATAPOS = 1;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_SECTORLABELS = 2;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_EXTRACTONBUILD = 3;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_ENTRYMAYCHANGE = 4;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_GUESSSECTORSIZE = 5;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_GUESSTOTALSECTORS = 6;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_GUESSCYLINDERS = 7;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_GUESSCYLSECTORS = 8;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_GUESSHEADS = 9;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_GUESSTRACKSECTORS = 10;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_GUESSLOWCYL = 11;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_GUESSHIGHCYL = 12;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_NOCYLINDERS = 15;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_NOCYLSECTORS = 16;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_NOHEADS = 17;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_NOTRACKSECTORS = 18;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_NOLOWCYL = 19;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIB_NOHIGHCYL = 20;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_CRYPTED = (1 << 0);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_SEEKDATAPOS = (1 << 1);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_SECTORLABELS = (1 << 2);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_EXTRACTONBUILD = (1 << 3);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_ENTRYMAYCHANGE = (1 << 4);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_GUESSSECTORSIZE = (1 << 5);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_GUESSTOTALSECTORS = (1 << 6);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_GUESSCYLINDERS = (1 << 7);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_GUESSCYLSECTORS = (1 << 8);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_GUESSHEADS = (1 << 9);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_GUESSTRACKSECTORS = (1 << 10);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_GUESSLOWCYL = (1 << 11);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_GUESSHIGHCYL = (1 << 12);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_NOCYLINDERS = (1 << 15);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_NOCYLSECTORS = (1 << 16);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_NOHEADS = (1 << 17);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_NOTRACKSECTORS = (1 << 18);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_NOLOWCYL = (1 << 19);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADDIF_NOHIGHCYL = (1 << 20);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADBIB_CLEARED = 0;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADBIB_UNUSED = 1;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADBIF_CLEARED = (1 << 0);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADBIF_UNUSED = (1 << 1);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPMODE_ASK = 1;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPMODE_PROGRESS = 2;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPMODE_END = 3;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPMODE_ERROR = 4;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPMODE_NEWENTRY = 5;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPMODE_GETINFOEND = 6;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPIB_OVERWRITE = 0;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPIB_MAKEDIRECTORY = 1;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPIB_IGNOREGEOMETRY = 2;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPIB_ISDIRECTORY = 3;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPIB_RENAME = 10;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPIB_OK = 16;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPIB_SKIP = 17;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPIF_OVERWRITE = (1 << 0);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPIF_MAKEDIRECTORY = (1 << 1);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPIF_IGNOREGEOMETRY = (1 << 2);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPIF_ISDIRECTORY = (1 << 3);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPIF_RENAME = (1 << 10);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPIF_OK = (1 << 16);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADPIF_SKIP = (1 << 17);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_OK = 0x0000;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_UNKNOWN = 0x0001;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_INPUT = 0x0002;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_OUTPUT = 0x0003;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_BADPARAMS = 0x0004;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_NOMEMORY = 0x0005;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_ILLEGALDATA = 0x0006;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_NOTSUPPORTED = 0x0007;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_RESOURCE = 0x0008;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_DECRUNCH = 0x0009;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_FILETYPE = 0x000A;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_OPENFILE = 0x000B;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_SKIP = 0x000C;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_BREAK = 0x000D;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_FILEEXISTS = 0x000E;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_PASSWORD = 0x000F;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_MAKEDIR = 0x0010;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_CHECKSUM = 0x0011;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_VERIFY = 0x0012;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_GEOMETRY = 0x0013;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_DATAFORMAT = 0x0014;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_EMPTY = 0x0015;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_FILESYSTEM = 0x0016;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_FILEDIR = 0x0017;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_SHORTBUFFER = 0x0018;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADERR_ENCODING = 0x0019;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int CHARSET_HOST = 0;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int CHARSET_UNICODE_UCS2_HOST = 10;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int CHARSET_UNICODE_UCS2_BIGENDIAN = 11;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int CHARSET_UNICODE_UCS2_LITTLEENDIAN = 12;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int CHARSET_UNICODE_UTF8 = 13;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int CHARSET_AMIGA = 100;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int CHARSET_MSDOS = 101;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int CHARSET_MACOS = 102;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int CHARSET_C64 = 103;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int CHARSET_ATARI_ST = 104;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int CHARSET_WINDOWS = 105;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int CHARSET_ASCII = 200;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int CHARSET_ISO_8859_1 = 201;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int CHARSET_ISO_8859_15 = 215;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int CHARSET_ATARI_ST_US = 300;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int CHARSET_PETSCII_C64_LC = 301;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int CHARSET_CODEPAGE_437 = 400;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int CHARSET_CODEPAGE_1252 = 401;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCLIENT_VERSION = 1;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCB_FILEARCHIVER = 0;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCB_DISKARCHIVER = 1;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCB_EXTERN = 2;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCB_FILESYSTEM = 3;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCB_NOCHECKSIZE = 4;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCB_DATACRUNCHER = 5;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCB_EXECRUNCHER = 6;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCB_ADDRESSCRUNCHER = 7;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCB_LINKER = 8;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCB_FREEXADSTRINGS = 25;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCB_FREESPECIALINFO = 26;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCB_FREESKIPINFO = 27;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCB_FREETEXTINFO = 28;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCB_FREETEXTINFOTEXT = 29;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCB_FREEFILEINFO = 30;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCB_FREEDISKINFO = 31;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCF_FILEARCHIVER = (1 << 0);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCF_DISKARCHIVER = (1 << 1);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCF_EXTERN = (1 << 2);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCF_FILESYSTEM = (1 << 3);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCF_NOCHECKSIZE = (1 << 4);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCF_DATACRUNCHER = (1 << 5);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCF_EXECRUNCHER = (1 << 6);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCF_ADDRESSCRUNCHER = (1 << 7);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCF_LINKER = (1 << 8);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCF_FREEXADSTRINGS = (1 << 25);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCF_FREESPECIALINFO = (1 << 26);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCF_FREESKIPINFO = (1 << 27);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCF_FREETEXTINFO = (1 << 28);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCF_FREETEXTINFOTEXT = (1 << 29);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCF_FREEFILEINFO = (1 << 30);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCF_FREEDISKINFO = (1 << 31);
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_XMASH = 1000;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_SUPERDUPER3 = 1001;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_XDISK = 1002;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_PACKDEV = 1003;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_ZOOM = 1004;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_ZOOM5 = 1005;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_CRUNCHDISK = 1006;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_PACKDISK = 1007;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_MDC = 1008;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_COMPDISK = 1009;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_LHWARP = 1010;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_SAVAGECOMPRESSOR = 1011;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_WARP = 1012;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_GDC = 1013;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_DCS = 1014;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_MSA = 1015;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_COP = 1016;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_DIMP = 1017;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_DIMPSFX = 1018;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_TAR = 5000;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_SDSSFX = 5001;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_LZX = 5002;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_MXMSIMPLEARC = 5003;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_LHPAK = 5004;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_AMIGAPLUSUNPACK = 5005;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_AMIPACK = 5006;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_LHA = 5007;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_LHASFX = 5008;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_PCOMPARC = 5009;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_SOMNI = 5010;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_LHSFX = 5011;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_XPKARCHIVE = 5012;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_SHRINK = 5013;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_SPACK = 5014;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_SPACKSFX = 5015;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_ZIP = 5016;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_WINZIPEXE = 5017;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_GZIP = 5018;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_ARC = 5019;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_ZOO = 5020;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_LHAEXE = 5021;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_ARJ = 5022;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_ARJEXE = 5023;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_ZIPEXE = 5024;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_LHF = 5025;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_COMPRESS = 5026;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_ACE = 5027;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_ACEEXE = 5028;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_GZIPSFX = 5029;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_HA = 5030;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_SQ = 5031;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_LHAC64SFX = 5032;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_SIT = 5033;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_SIT5 = 5034;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_SIT5EXE = 5035;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_MACBINARY = 5036;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_CPIO = 5037;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_PACKIT = 5038;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_CRUNCH = 5039;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_ARCCBM = 5040;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_ARCCBMSFX = 5041;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_CAB = 5042;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_CABMSEXE = 5043;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_RPM = 5044;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_BZIP2 = 5045;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_BZIP2SFX = 5046;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_BZIP = 5047;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_IDPAK = 5048;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_IDWAD = 5049;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_IDWAD2 = 5050;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_RAR = 5051;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_BINHEX = 5052;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_SEVENZIP = 5053;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_FSAMIGA = 8000;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_FSSANITYOS = 8001;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_FSFAT = 8002;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_FSTRDOS = 8003;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_DMS = 9000;
	/** <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h</i> */
	int XADCID_DMSSFX = 9001;
	/**
	 * BEGIN auto-generated section (EXTERNAL VARARGS)<br>
	 * Original signature : <code>xadMasterBase* xadOpenLibrary(xadINT32)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:913</i>
	 */
	xadMasterBase xadOpenLibrary(int version);
	/**
	 * Original signature : <code>void xadCloseLibrary(xadMasterBase*)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:914</i>
	 */
	void xadCloseLibrary(xadMasterBase xadMasterBasePtr1);
	/**
	 * Original signature : <code>xadERROR xadAddDiskEntry(xadMasterBase*, xadDiskInfo*, xadArchiveInfo*, xadTag, null)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:915</i>
	 */
	int xadAddDiskEntry(xadMasterBase xadMasterBase, xadDiskInfo di, xadArchiveInfo ai, int tag, Object... varArgs1);
	/**
	 * Original signature : <code>xadERROR xadAddDiskEntryA(xadMasterBase*, xadDiskInfo*, xadArchiveInfo*, xadTAGPTR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:916</i>
	 */
	int xadAddDiskEntryA(xadMasterBase xadMasterBase, xadDiskInfo di, xadArchiveInfo ai, TagItem tags);
	/**
	 * Original signature : <code>xadERROR xadAddFileEntry(xadMasterBase*, xadFileInfo*, xadArchiveInfo*, xadTag, null)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:917</i>
	 */
	int xadAddFileEntry(xadMasterBase xadMasterBase, xadFileInfo fi, xadArchiveInfo ai, int tag, Object... varArgs1);
	/**
	 * Original signature : <code>xadERROR xadAddFileEntryA(xadMasterBase*, xadFileInfo*, xadArchiveInfo*, xadTAGPTR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:918</i>
	 */
	int xadAddFileEntryA(xadMasterBase xadMasterBase, xadFileInfo fi, xadArchiveInfo ai, TagItem tags);
	/**
	 * Original signature : <code>xadPTR xadAllocObject(xadMasterBase*, xadUINT32, xadTag, null)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:919</i>
	 */
	Pointer xadAllocObject(xadMasterBase xadMasterBase, int type, int tag, Object... varArgs1);
	/**
	 * Original signature : <code>xadPTR xadAllocObjectA(xadMasterBase*, xadUINT32, xadTAGPTR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:920</i>
	 */
	Pointer xadAllocObjectA(xadMasterBase xadMasterBase, int type, TagItem tags);
	/**
	 * Original signature : <code>xadPTR xadAllocVec(xadMasterBase*, xadSize, xadUINT32)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:921</i>
	 */
	Pointer xadAllocVec(xadMasterBase xadMasterBase, long size, int flags);
	/**
	 * Original signature : <code>xadUINT16 xadCalcCRC16(xadMasterBase*, xadUINT16, xadUINT16, xadSize, const xadUINT8*)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:922</i><br>
	 * @deprecated use the safer methods {@link #xadCalcCRC16(vavi.util.archive.unar.xadmaster.xadMasterBase, short, short, long, java.nio.ByteBuffer)} and {@link #xadCalcCRC16(vavi.util.archive.unar.xadmaster.xadMasterBase, short, short, long, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	short xadCalcCRC16(xadMasterBase xadMasterBase, short id, short init, long size, Pointer buffer);
	/**
	 * Original signature : <code>xadUINT16 xadCalcCRC16(xadMasterBase*, xadUINT16, xadUINT16, xadSize, const xadUINT8*)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:922</i>
	 */
	short xadCalcCRC16(xadMasterBase xadMasterBase, short id, short init, long size, ByteBuffer buffer);
	/**
	 * Original signature : <code>xadUINT32 xadCalcCRC32(xadMasterBase*, xadUINT32, xadUINT32, xadSize, const xadUINT8*)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:923</i><br>
	 * @deprecated use the safer methods {@link #xadCalcCRC32(vavi.util.archive.unar.xadmaster.xadMasterBase, int, int, long, java.nio.ByteBuffer)} and {@link #xadCalcCRC32(vavi.util.archive.unar.xadmaster.xadMasterBase, int, int, long, com.sun.jna.Pointer)} instead
	 */
	@Deprecated 
	int xadCalcCRC32(xadMasterBase xadMasterBase, int id, int init, long size, Pointer buffer);
	/**
	 * Original signature : <code>xadUINT32 xadCalcCRC32(xadMasterBase*, xadUINT32, xadUINT32, xadSize, const xadUINT8*)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:923</i>
	 */
	int xadCalcCRC32(xadMasterBase xadMasterBase, int id, int init, long size, ByteBuffer buffer);
	/**
	 * Original signature : <code>xadERROR xadConvertDates(xadMasterBase*, xadTag, null)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:924</i>
	 */
	int xadConvertDates(xadMasterBase xadMasterBase, int tag, Object... varArgs1);
	/**
	 * Original signature : <code>xadERROR xadConvertDatesA(xadMasterBase*, xadTAGPTR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:925</i>
	 */
	int xadConvertDatesA(xadMasterBase xadMasterBase, TagItem tags);
	/**
	 * Original signature : <code>xadSTRPTR xadConvertName(xadMasterBase*, xadUINT32, xadTag, null)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:926</i>
	 */
	Pointer xadConvertName(xadMasterBase xadMasterBase, int charset, int tag, Object... varArgs1);
	/**
	 * Original signature : <code>xadSTRPTR xadConvertNameA(xadMasterBase*, xadUINT32, xadTAGPTR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:927</i>
	 */
	Pointer xadConvertNameA(xadMasterBase xadMasterBase, int charset, TagItem tags);
	/**
	 * Original signature : <code>xadERROR xadConvertProtection(xadMasterBase*, xadTag, null)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:928</i>
	 */
	int xadConvertProtection(xadMasterBase xadMasterBase, int tag, Object... varArgs1);
	/**
	 * Original signature : <code>xadERROR xadConvertProtectionA(xadMasterBase*, xadTAGPTR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:929</i>
	 */
	int xadConvertProtectionA(xadMasterBase xadMasterBase, TagItem tags);
	/**
	 * Original signature : <code>void xadCopyMem(xadMasterBase*, const void*, xadPTR, xadSize)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:930</i>
	 */
	void xadCopyMem(xadMasterBase xadMasterBase, Pointer s, Pointer d, long size);
	/**
	 * Original signature : <code>xadERROR xadDiskUnArc(xadMasterBase*, xadArchiveInfo*, xadTag, null)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:931</i>
	 */
	int xadDiskUnArc(xadMasterBase xadMasterBase, xadArchiveInfo ai, int tag, Object... varArgs1);
	/**
	 * Original signature : <code>xadERROR xadDiskUnArcA(xadMasterBase*, xadArchiveInfo*, xadTAGPTR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:932</i>
	 */
	int xadDiskUnArcA(xadMasterBase xadMasterBase, xadArchiveInfo ai, TagItem tags);
	/**
	 * Original signature : <code>xadERROR xadFileUnArc(xadMasterBase*, xadArchiveInfo*, xadTag, null)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:933</i>
	 */
	int xadFileUnArc(xadMasterBase xadMasterBase, xadArchiveInfo ai, int tag, Object... varArgs1);
	/**
	 * Original signature : <code>xadERROR xadFileUnArcA(xadMasterBase*, xadArchiveInfo*, xadTAGPTR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:934</i>
	 */
	int xadFileUnArcA(xadMasterBase xadMasterBase, xadArchiveInfo ai, TagItem tags);
	/**
	 * Original signature : <code>void xadFreeHookAccess(xadMasterBase*, xadArchiveInfo*, xadTag, null)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:935</i>
	 */
	void xadFreeHookAccess(xadMasterBase xadMasterBase, xadArchiveInfo ai, int tag, Object... varArgs1);
	/**
	 * Original signature : <code>void xadFreeHookAccessA(xadMasterBase*, xadArchiveInfo*, xadTAGPTR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:936</i>
	 */
	void xadFreeHookAccessA(xadMasterBase xadMasterBase, xadArchiveInfo ai, TagItem tags);
	/**
	 * Original signature : <code>void xadFreeInfo(xadMasterBase*, xadArchiveInfo*)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:937</i>
	 */
	void xadFreeInfo(xadMasterBase xadMasterBase, xadArchiveInfo ai);
	/**
	 * Original signature : <code>void xadFreeObject(xadMasterBase*, xadPTR, xadTag, null)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:938</i>
	 */
	void xadFreeObject(xadMasterBase xadMasterBase, Pointer object, int tag, Object... varArgs1);
	/**
	 * Original signature : <code>void xadFreeObjectA(xadMasterBase*, xadPTR, xadTAGPTR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:939</i>
	 */
	void xadFreeObjectA(xadMasterBase xadMasterBase, Pointer object, TagItem tags);
	/**
	 * Original signature : <code>xadClient* xadGetClientInfo(xadMasterBase*)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:940</i>
	 */
	xadClient xadGetClientInfo(xadMasterBase xadMasterBase);
	/**
	 * Original signature : <code>xadSTRPTR xadGetDefaultName(xadMasterBase*, xadTag, null)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:941</i>
	 */
	Pointer xadGetDefaultName(xadMasterBase xadMasterBase, int tag, Object... varArgs1);
	/**
	 * Original signature : <code>xadSTRPTR xadGetDefaultNameA(xadMasterBase*, xadTAGPTR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:942</i>
	 */
	Pointer xadGetDefaultNameA(xadMasterBase xadMasterBase, TagItem tags);
	/**
	 * Original signature : <code>xadERROR xadGetDiskInfo(xadMasterBase*, xadArchiveInfo*, xadTag, null)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:943</i>
	 */
	int xadGetDiskInfo(xadMasterBase xadMasterBase, xadArchiveInfo ai, int tag, Object... varArgs1);
	/**
	 * Original signature : <code>xadERROR xadGetDiskInfoA(xadMasterBase*, xadArchiveInfo*, xadTAGPTR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:944</i>
	 */
	int xadGetDiskInfoA(xadMasterBase xadMasterBase, xadArchiveInfo ai, TagItem tags);
	/**
	 * Original signature : <code>xadSTRPTR xadGetErrorText(xadMasterBase*, xadERROR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:945</i>
	 */
	Pointer xadGetErrorText(xadMasterBase xadMasterBase, int errnum);
	/**
	 * Original signature : <code>xadERROR xadGetFilename(xadMasterBase*, xadUINT32, xadSTRPTR, const xadSTRING*, const xadSTRING*, xadTag, null)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:946</i><br>
	 * @deprecated use the safer methods {@link #xadGetFilename(vavi.util.archive.unar.xadmaster.xadMasterBase, int, java.nio.ByteBuffer, java.nio.ByteBuffer, java.nio.ByteBuffer, int, java.lang.Object...)} and {@link #xadGetFilename(vavi.util.archive.unar.xadmaster.xadMasterBase, int, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, int, java.lang.Object...)} instead
	 */
	@Deprecated 
	int xadGetFilename(xadMasterBase xadMasterBase, int buffersize, Pointer buffer, Pointer path, Pointer name, int tag, Object... varArgs1);
	/**
	 * Original signature : <code>xadERROR xadGetFilename(xadMasterBase*, xadUINT32, xadSTRPTR, const xadSTRING*, const xadSTRING*, xadTag, null)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:946</i>
	 */
	int xadGetFilename(xadMasterBase xadMasterBase, int buffersize, ByteBuffer buffer, ByteBuffer path, ByteBuffer name, int tag, Object... varArgs1);
	/**
	 * Original signature : <code>xadERROR xadGetFilenameA(xadMasterBase*, xadUINT32, xadSTRPTR, const xadSTRING*, const xadSTRING*, xadTAGPTR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:947</i><br>
	 * @deprecated use the safer methods {@link #xadGetFilenameA(vavi.util.archive.unar.xadmaster.xadMasterBase, int, java.nio.ByteBuffer, java.nio.ByteBuffer, java.nio.ByteBuffer, vavi.util.archive.unar.xadmaster.TagItem)} and {@link #xadGetFilenameA(vavi.util.archive.unar.xadmaster.xadMasterBase, int, com.sun.jna.Pointer, com.sun.jna.Pointer, com.sun.jna.Pointer, vavi.util.archive.unar.xadmaster.TagItem)} instead
	 */
	@Deprecated 
	int xadGetFilenameA(xadMasterBase xadMasterBase, int buffersize, Pointer buffer, Pointer path, Pointer name, TagItem tags);
	/**
	 * Original signature : <code>xadERROR xadGetFilenameA(xadMasterBase*, xadUINT32, xadSTRPTR, const xadSTRING*, const xadSTRING*, xadTAGPTR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:947</i>
	 */
	int xadGetFilenameA(xadMasterBase xadMasterBase, int buffersize, ByteBuffer buffer, ByteBuffer path, ByteBuffer name, TagItem tags);
	/**
	 * Original signature : <code>xadERROR xadGetInfo(xadMasterBase*, xadArchiveInfo*, xadTag, null)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:948</i>
	 */
	int xadGetInfo(xadMasterBase xadMasterBase, xadArchiveInfo ai, int tag, Object... varArgs1);
	/**
	 * Original signature : <code>xadERROR xadGetInfoA(xadMasterBase*, xadArchiveInfo*, xadTAGPTR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:949</i>
	 */
	int xadGetInfoA(xadMasterBase xadMasterBase, xadArchiveInfo ai, TagItem tags);
	/**
	 * Original signature : <code>xadERROR xadGetHookAccess(xadMasterBase*, xadArchiveInfo*, xadTag, null)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:950</i>
	 */
	int xadGetHookAccess(xadMasterBase xadMasterBase, xadArchiveInfo ai, int tag, Object... varArgs1);
	/**
	 * Original signature : <code>xadERROR xadGetHookAccessA(xadMasterBase*, xadArchiveInfo*, xadTAGPTR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:951</i>
	 */
	int xadGetHookAccessA(xadMasterBase xadMasterBase, xadArchiveInfo ai, TagItem tags);
	/**
	 * Original signature : <code>xadSystemInfo* xadGetSystemInfo(xadMasterBase*)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:952</i>
	 */
	xadSystemInfo xadGetSystemInfo(xadMasterBase xadMasterBase);
	/**
	 * Original signature : <code>xadERROR xadHookAccess(xadMasterBase*, xadUINT32, xadSignSize, xadPTR, xadArchiveInfo*)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:953</i>
	 */
	int xadHookAccess(xadMasterBase xadMasterBase, int command, long data, Pointer buffer, xadArchiveInfo ai);
	/**
	 * Original signature : <code>xadERROR xadHookTagAccess(xadMasterBase*, xadUINT32, xadSignSize, xadPTR, xadArchiveInfo*, xadTag, null)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:954</i>
	 */
	int xadHookTagAccess(xadMasterBase xadMasterBase, int command, long data, Pointer buffer, xadArchiveInfo ai, int tag, Object... varArgs1);
	/**
	 * Original signature : <code>xadERROR xadHookTagAccessA(xadMasterBase*, xadUINT32, xadSignSize, xadPTR, xadArchiveInfo*, xadTAGPTR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:955</i>
	 */
	int xadHookTagAccessA(xadMasterBase xadMasterBase, int command, long data, Pointer buffer, xadArchiveInfo ai, TagItem tags);
	/**
	 * Original signature : <code>xadClient* xadRecogFile(xadMasterBase*, xadSize, const void*, xadTag, null)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:956</i>
	 */
	xadClient xadRecogFile(xadMasterBase xadMasterBase, long size, Pointer mem, int tag, Object... varArgs1);
	/**
	 * Original signature : <code>xadClient* xadRecogFileA(xadMasterBase*, xadSize, const void*, xadTAGPTR)</code><br>
	 * <i>native declaration : XADMaster.framework/Versions/A/Headers/xadmaster.h:957</i>
	 */
	xadClient xadRecogFileA(xadMasterBase xadMasterBase, long size, Pointer mem, TagItem tags);
}
