package vavi.util.archive.unar.xadmaster;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * *<br>
 *    system information structure                                       *<br>
 *                                                                       *<br>
 * **********************************************************************<br>
 * <i>native declaration : /Frameworks/XADMaster.framework/Versions/A/Headers/xadmaster.h:302</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xadSystemInfo extends Structure {
	/**
	 * master library version<br>
	 * C type : xadUINT16
	 */
	public short xsi_Version;
	/**
	 * master library revision<br>
	 * C type : xadUINT16
	 */
	public short xsi_Revision;
	/**
	 * size for recognition<br>
	 * C type : xadSize
	 */
	public long xsi_RecogSize;
	public xadSystemInfo() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("xsi_Version", "xsi_Revision", "xsi_RecogSize");
	}
	/**
	 * @param xsi_Version master library version<br>
	 * C type : xadUINT16<br>
	 * @param xsi_Revision master library revision<br>
	 * C type : xadUINT16<br>
	 * @param xsi_RecogSize size for recognition<br>
	 * C type : xadSize
	 */
	public xadSystemInfo(short xsi_Version, short xsi_Revision, long xsi_RecogSize) {
		super();
		this.xsi_Version = xsi_Version;
		this.xsi_Revision = xsi_Revision;
		this.xsi_RecogSize = xsi_RecogSize;
	}
	public xadSystemInfo(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xadSystemInfo implements Structure.ByReference {
	}
	public static class ByValue extends xadSystemInfo implements Structure.ByValue {
	}
}
