package vavi.util.archive.unar.xadmaster;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * <i>native declaration : /Frameworks/XADMaster.framework/Versions/A/Headers/xadmaster.h:432</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xadSpecialCBM8bit extends Structure {
	/**
	 * File type XADCBM8BITTYPE_xxx<br>
	 * C type : xadUINT8
	 */
	public byte xfis_FileType;
	/**
	 * record length if relative file<br>
	 * C type : xadUINT8
	 */
	public byte xfis_RecordLength;
	public xadSpecialCBM8bit() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("xfis_FileType", "xfis_RecordLength");
	}
	/**
	 * @param xfis_FileType File type XADCBM8BITTYPE_xxx<br>
	 * C type : xadUINT8<br>
	 * @param xfis_RecordLength record length if relative file<br>
	 * C type : xadUINT8
	 */
	public xadSpecialCBM8bit(byte xfis_FileType, byte xfis_RecordLength) {
		super();
		this.xfis_FileType = xfis_FileType;
		this.xfis_RecordLength = xfis_RecordLength;
	}
	public xadSpecialCBM8bit(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xadSpecialCBM8bit implements Structure.ByReference {
		
	};
	public static class ByValue extends xadSpecialCBM8bit implements Structure.ByValue {
		
	};
}
