package vavi.util.archive.unar.xadmaster;
import com.sun.jna.Pointer;
import com.sun.jna.Structure;
import java.util.Arrays;
import java.util.List;
/**
 * for XAD_INSPLITTED<br>
 * <i>native declaration : /Frameworks/XADMaster.framework/Versions/A/Headers/xadmaster.h:273</i><br>
 * This file was autogenerated by <a href="http://jnaerator.googlecode.com/">JNAerator</a>,<br>
 * a tool written by <a href="http://ochafik.com/">Olivier Chafik</a> that <a href="http://code.google.com/p/jnaerator/wiki/CreditsAndLicense">uses a few opensource projects.</a>.<br>
 * For help, please visit <a href="http://nativelibs4java.googlecode.com/">NativeLibs4Java</a> , <a href="http://rococoa.dev.java.net/">Rococoa</a>, or <a href="http://jna.dev.java.net/">JNA</a>.
 */
public class xadSplitFile extends Structure {
	/** C type : xadSplitFile* */
	public xadSplitFile.ByReference xsf_Next;
	/**
	 * XAD_INFILENAME, XAD_INFILEHANDLE, XAD_INMEMORY, XAD_INHOOK<br>
	 * C type : xadUINT32
	 */
	public int xsf_Type;
	/**
	 * necessary for XAD_INMEMORY, useful for others<br>
	 * C type : xadSize
	 */
	public long xsf_Size;
	/**
	 * FileName, Filehandle, Hookpointer or Memory<br>
	 * C type : xadSize
	 */
	public long xsf_Data;
	public xadSplitFile() {
		super();
	}
	protected List<String> getFieldOrder() {
		return Arrays.asList("xsf_Next", "xsf_Type", "xsf_Size", "xsf_Data");
	}
	/**
	 * @param xsf_Next C type : xadSplitFile*<br>
	 * @param xsf_Type XAD_INFILENAME, XAD_INFILEHANDLE, XAD_INMEMORY, XAD_INHOOK<br>
	 * C type : xadUINT32<br>
	 * @param xsf_Size necessary for XAD_INMEMORY, useful for others<br>
	 * C type : xadSize<br>
	 * @param xsf_Data FileName, Filehandle, Hookpointer or Memory<br>
	 * C type : xadSize
	 */
	public xadSplitFile(xadSplitFile.ByReference xsf_Next, int xsf_Type, long xsf_Size, long xsf_Data) {
		super();
		this.xsf_Next = xsf_Next;
		this.xsf_Type = xsf_Type;
		this.xsf_Size = xsf_Size;
		this.xsf_Data = xsf_Data;
	}
	public xadSplitFile(Pointer peer) {
		super(peer);
	}
	public static class ByReference extends xadSplitFile implements Structure.ByReference {
	}
	public static class ByValue extends xadSplitFile implements Structure.ByValue {
	}
}
