name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-14

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check w/o SNAPSHOT when "bump version"
      if: ${{ contains(github.event.head_commit.message, 'bump version') }}
      run: grep "<version>" pom.xml | head -1 | grep -v SNAPSHOT

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: |
        brew install unar
        v=brew info unar | grep stable | awk '{print $4}'
        echo $v
        mkdir -p ~/Library/Frameworks
        (cd ~/Library/Frameworks; ln -s /opt/homebrew/Cellar/xad/$v/Frameworks/UniversalDetector.framework .)
        (cd ~/Library/Frameworks; ln -s /opt/homebrew/Cellar/xad/$v/Frameworks/XADMaster.framework .)
        ls -l ~/Library/Frameworks/
        mvn -B package --file pom.xml -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
